### ISSUE TITLE
成功排牙，但是有的牙齿的角度没有很好

### ISSUE THREAD

**Issue by Lahahaha** [yeyuxmf/auto_tooth_arrangement#14]
感谢您分享的开源项目。成功排牙，但是有的牙齿的角度没有很好。请问这种情况是最好是增加训练数据解决吗，如果没有很多数据集，那在网络结构的调整或训练策略上有没有好的建议。
![image](https://github.com/huang229/auto_tooth_arrangement/assets/39371216/6a21dade-53d8-4841-93bb-10fcce65c33d)
另外，我有一个思考，如果能将牙齿模型三角面片相关的信息输入网络，以点云+三角面片特征的方式训练感觉可以为模型提供更有用的信息

**Comment by yeyuxmf** [comment]
@Lahahaha 
1. 你反应的这个问题，极少数会发生，应该在5%以下，具体没统计，数据越多越不容易出现此种情况，此外最远距离采样点也会减少这样的概率。
2. 不知道你是用无限模拟正畸前的数据训练，然后直接测试真实正畸前的数据还是测试的模拟正畸前的数据，此外训练时是否添加真实数据对。
3. 从这口排牙来看，你的效果与我自己跑的差距不小，碰撞这么严重。
4. 不要打开我关掉的损失函数，那是微调用的。
5. 这个开源速度快且有效的范式，输入根据你具体情况而定（比如论文刷精度）。
6. 可以给微信号讨论。

**Comment by Lahahaha** [comment]
好的感谢，我犯了低级错误，有一些脏数据影响了训练😂。我再尝试按照您的思路做一些网络结构改变，试试效果。先关闭这个issue了
